#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1528785549.914696
__CHEETAH_genTimestamp__ = 'Tue Jun 12 03:39:09 2018'
__CHEETAH_src__ = '../m/cable.tmpl'
__CHEETAH_srcLastModified__ = 'Tue Jun 12 03:38:08 2018'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class cable(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(cable, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''auto ''')
        _v = VFFSL(SL,"interfaces.cable",True) # u'${interfaces.cable}' on line 1, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'${interfaces.cable}')) # from line 1, col 6.
        write(u'''
iface ''')
        _v = VFFSL(SL,"interfaces.cable",True) # u'${interfaces.cable}' on line 2, col 7
        if _v is not None: write(_filter(_v, rawExpr=u'${interfaces.cable}')) # from line 2, col 7.
        write(u''' inet static
address ''')
        _v = VFFSL(SL,"ip.address",True) # u'${ip.address}' on line 3, col 9
        if _v is not None: write(_filter(_v, rawExpr=u'${ip.address}')) # from line 3, col 9.
        write(u'''
netmask ''')
        _v = VFFSL(SL,"ip.netmask",True) # u'${ip.netmask}' on line 4, col 9
        if _v is not None: write(_filter(_v, rawExpr=u'${ip.netmask}')) # from line 4, col 9.
        write(u'''
network ''')
        _v = VFFSL(SL,"ip.network",True) # u'${ip.network}' on line 5, col 9
        if _v is not None: write(_filter(_v, rawExpr=u'${ip.network}')) # from line 5, col 9.
        write(u'''
gateway ''')
        _v = VFFSL(SL,"ip.gateway",True) # u'${ip.gateway}' on line 6, col 9
        if _v is not None: write(_filter(_v, rawExpr=u'${ip.gateway}')) # from line 6, col 9.
        write(u'''
dns-nameservers ''')
        _v = VFFSL(SL,"ip.dns",True) # u'${ip.dns}' on line 7, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'${ip.dns}')) # from line 7, col 17.
        write(u'''

''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_cable= 'respond'

## END CLASS DEFINITION

if not hasattr(cable, '_initCheetahAttributes'):
    templateAPIClass = getattr(cable, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(cable)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=cable()).run()


