#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1511304366.538517
__CHEETAH_genTimestamp__ = 'Tue Nov 21 20:46:06 2017'
__CHEETAH_src__ = '../m/StoppedState_c.tmpl'
__CHEETAH_srcLastModified__ = 'Tue Nov 21 20:46:01 2017'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class StoppedState_c(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(StoppedState_c, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''#include "''')
        _v = VFN(VFFSL(SL,"state.stop.name",True),"capitalize",False)() # u'${state.stop.name.capitalize()}' on line 1, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'${state.stop.name.capitalize()}')) # from line 1, col 12.
        write(u'''State.h"
#include "''')
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # u'${state.name.capitalize()}' on line 2, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'${state.name.capitalize()}')) # from line 2, col 12.
        write(u'''StateInternal.h"

/* Possible transition to the following state: */
#include "''')
        _v = VFN(VFFSL(SL,"state.stop.to",True),"capitalize",False)() # u'${state.stop.to.capitalize()}' on line 5, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'${state.stop.to.capitalize()}')) # from line 5, col 12.
        write(u'''State.h"

#include "message.h" // DEBUG

static void ''')
        _v = VFFSL(SL,"state.stop.to",True) # u'${state.stop.to}' on line 9, col 13
        if _v is not None: write(_filter(_v, rawExpr=u'${state.stop.to}')) # from line 9, col 13.
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # u'${state.name.capitalize()}' on line 9, col 29
        if _v is not None: write(_filter(_v, rawExpr=u'${state.name.capitalize()}')) # from line 9, col 29.
        write(u''' (''')
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # u'${state.name.capitalize()}' on line 9, col 57
        if _v is not None: write(_filter(_v, rawExpr=u'${state.name.capitalize()}')) # from line 9, col 57.
        write(u'''StatePtr state)
{
    message("** ''')
        _v = VFFSL(SL,"state.stop.to",True) # u'${state.stop.to}' on line 11, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'${state.stop.to}')) # from line 11, col 17.
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # u'${state.name.capitalize()}' on line 11, col 33
        if _v is not None: write(_filter(_v, rawExpr=u'${state.name.capitalize()}')) # from line 11, col 33.
        write(u''' **");

    ''')
        _v = VFFSL(SL,"state.transitionTo.name",True) # u'${state.transitionTo.name}' on line 13, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'${state.transitionTo.name}')) # from line 13, col 5.
        _v = VFN(VFFSL(SL,"state.stop.to",True),"capitalize",False)() # u'${state.stop.to.capitalize()}' on line 13, col 31
        if _v is not None: write(_filter(_v, rawExpr=u'${state.stop.to.capitalize()}')) # from line 13, col 31.
        write(u''' (state);
}

void ''')
        _v = VFFSL(SL,"state.transitionTo.name",True) # u'${state.transitionTo.name}' on line 16, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'${state.transitionTo.name}')) # from line 16, col 6.
        _v = VFN(VFFSL(SL,"state.stop.name",True),"capitalize",False)() # u'${state.stop.name.capitalize()}' on line 16, col 32
        if _v is not None: write(_filter(_v, rawExpr=u'${state.stop.name.capitalize()}')) # from line 16, col 32.
        write(u''' (''')
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # u'${state.name.capitalize()}' on line 16, col 65
        if _v is not None: write(_filter(_v, rawExpr=u'${state.name.capitalize()}')) # from line 16, col 65.
        write(u'''StatePtr state)
{
    message("** ''')
        _v = VFFSL(SL,"state.transitionTo.name",True) # u'${state.transitionTo.name}' on line 18, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'${state.transitionTo.name}')) # from line 18, col 17.
        _v = VFN(VFFSL(SL,"state.stop.name",True),"capitalize",False)() # u'${state.stop.name.capitalize()}' on line 18, col 43
        if _v is not None: write(_filter(_v, rawExpr=u'${state.stop.name.capitalize()}')) # from line 18, col 43.
        write(u''' **");

    /* Initialize with the default implementation before
       specifying the events to be handled in the stoped
       state. */

    ''')
        _v = VFFSL(SL,"state.defaultImplementation.name",True) # u'${state.defaultImplementation.name}' on line 24, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'${state.defaultImplementation.name}')) # from line 24, col 5.
        write(u''' (state);
    state->func = ''')
        _v = VFFSL(SL,"state.stop.to",True) # u'${state.stop.to}' on line 25, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'${state.stop.to}')) # from line 25, col 19.
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # u'${state.name.capitalize()}' on line 25, col 35
        if _v is not None: write(_filter(_v, rawExpr=u'${state.name.capitalize()}')) # from line 25, col 35.
        write(u''';
}

''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_StoppedState_c= 'respond'

## END CLASS DEFINITION

if not hasattr(StoppedState_c, '_initCheetahAttributes'):
    templateAPIClass = getattr(StoppedState_c, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(StoppedState_c)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=StoppedState_c()).run()


