#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.2.4'
__CHEETAH_versionTuple__ = (3, 2, 4, 'final', 0)
__CHEETAH_genTime__ = 1582600085.1319644
__CHEETAH_genTimestamp__ = 'Tue Feb 25 00:08:05 2020'
__CHEETAH_src__ = '../m/plugin__amake_vim.tmpl'
__CHEETAH_srcLastModified__ = 'Fri Dec 20 10:12:36 2019'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class plugin__amake_vim(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(plugin__amake_vim, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''" plugin/''')
        _v = VFFSL(SL,"cmd.name",True) # '${cmd.name}' on line 1, col 10
        if _v is not None: write(_filter(_v, rawExpr='${cmd.name}')) # from line 1, col 10.
        write(""".vim

if exists('g:loaded_""")
        _v = VFFSL(SL,"cmd.name",True) # '${cmd.name}' on line 3, col 21
        if _v is not None: write(_filter(_v, rawExpr='${cmd.name}')) # from line 3, col 21.
        write("""')
  finish
endif
let g:loaded_""")
        _v = VFFSL(SL,"cmd.name",True) # '${cmd.name}' on line 6, col 14
        if _v is not None: write(_filter(_v, rawExpr='${cmd.name}')) # from line 6, col 14.
        write(''' = 1

command! ''')
        _v = VFN(VFFSL(SL,"cmd.name",True),"title",False)() # '${cmd.name.title()}' on line 8, col 10
        if _v is not None: write(_filter(_v, rawExpr='${cmd.name.title()}')) # from line 8, col 10.
        write(''' call ''')
        _v = VFFSL(SL,"cmd.name",True) # '${cmd.name}' on line 8, col 35
        if _v is not None: write(_filter(_v, rawExpr='${cmd.name}')) # from line 8, col 35.
        write('''#hello_world()
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_plugin__amake_vim = 'respond'

## END CLASS DEFINITION

if not hasattr(plugin__amake_vim, '_initCheetahAttributes'):
    templateAPIClass = getattr(plugin__amake_vim,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(plugin__amake_vim)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit https://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=plugin__amake_vim()).run()


