#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.2.5a0'
__CHEETAH_versionTuple__ = (3, 2, 5, 'alpha', 0)
__CHEETAH_genTime__ = 1576846547.137906
__CHEETAH_genTimestamp__ = 'Fri Dec 20 09:55:47 2019'
__CHEETAH_src__ = '../m/etc__completion_bash.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Mar 20 17:34:23 2019'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class etc__completion_bash(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(etc__completion_bash, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''_''')
        _v = VFFSL(SL,"cmd.name",True) # '${cmd.name}' on line 1, col 2
        if _v is not None: write(_filter(_v, rawExpr='${cmd.name}')) # from line 1, col 2.
        write('''()
{
    COMPREPLY=()
    local word="${COMP_WORDS[COMP_CWORD]}"

    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "$(''')
        _v = VFFSL(SL,"cmd.name",True) # '${cmd.name}' on line 7, col 39
        if _v is not None: write(_filter(_v, rawExpr='${cmd.name}')) # from line 7, col 39.
        write(''' commands)" -- "$word") )
    # else
    #     local words=("${COMP_WORDS[''')
        _v = VFFSL(SL,"unicode.at",True) # '${unicode.at}' on line 9, col 40
        if _v is not None: write(_filter(_v, rawExpr='${unicode.at}')) # from line 9, col 40.
        write(''']}")

    #     case x${words[1]} in
    #         xnew)
    #             unset words[0]
    #             unset words[$COMP_CWORD]
    #             local completions=$(''')
        _v = VFFSL(SL,"cmd.name",True) # '${cmd.name}' on line 15, col 41
        if _v is not None: write(_filter(_v, rawExpr='${cmd.name}')) # from line 15, col 41.
        write(''' new -l "${words[''')
        _v = VFFSL(SL,"unicode.at",True) # '${unicode.at}' on line 15, col 70
        if _v is not None: write(_filter(_v, rawExpr='${unicode.at}')) # from line 15, col 70.
        write(''']}" )
    #             COMPREPLY=( $(compgen -W "$completions" -- "$word") )
    #         ;;
    #     esac

    fi
}
complete -F _''')
        _v = VFFSL(SL,"cmd.name",True) # '${cmd.name}' on line 22, col 14
        if _v is not None: write(_filter(_v, rawExpr='${cmd.name}')) # from line 22, col 14.
        write(''' ''')
        _v = VFFSL(SL,"cmd.name",True) # '${cmd.name}' on line 22, col 26
        if _v is not None: write(_filter(_v, rawExpr='${cmd.name}')) # from line 22, col 26.
        write('''
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_etc__completion_bash = 'respond'

## END CLASS DEFINITION

if not hasattr(etc__completion_bash, '_initCheetahAttributes'):
    templateAPIClass = getattr(etc__completion_bash,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(etc__completion_bash)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit https://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=etc__completion_bash()).run()


