#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.2.5a0'
__CHEETAH_versionTuple__ = (3, 2, 5, 'alpha', 0)
__CHEETAH_genTime__ = 1576846544.2177377
__CHEETAH_genTimestamp__ = 'Fri Dec 20 09:55:44 2019'
__CHEETAH_src__ = '../m/template.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Mar 20 17:34:23 2019'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class template(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(template, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''b.module.require opt

b.module.require options
b.module.require config
b.module.require exception
b.module.require exit


function try_again () {
    echo \\
    "Ocorreu um erro, verifique o output ou rode os testes para descobrir o erro"
}

# Run!
function run () {

    if ! ''')
        _v = VFFSL(SL,"cmd.name",True) # '${cmd.name}' on line 17, col 10
        if _v is not None: write(_filter(_v, rawExpr='${cmd.name}')) # from line 17, col 10.
        write('''.config.load; then
        return 1
    fi

    if [ -n "$1" ]; then

        case x$1 in
        xcommands|xcompletions|xusage)
            b.task.run "$''')
        _v = VFFSL(SL,"unicode.at",True) # '${unicode.at}' on line 25, col 27
        if _v is not None: write(_filter(_v, rawExpr='${unicode.at}')) # from line 25, col 27.
        write('''"
        ;;
        xinit)
            b.task.run "$''')
        _v = VFFSL(SL,"unicode.at",True) # '${unicode.at}' on line 28, col 27
        if _v is not None: write(_filter(_v, rawExpr='${unicode.at}')) # from line 28, col 27.
        write('''"
        ;;
        xtasks)
            echo enable $''')
        _v = VFFSL(SL,"unicode.at",True) # '${unicode.at}' on line 31, col 27
        if _v is not None: write(_filter(_v, rawExpr='${unicode.at}')) # from line 31, col 27.
        write(''':
            b.task.run "commands"
        ;;
        xoptions)
            echo enable $''')
        _v = VFFSL(SL,"unicode.at",True) # '${unicode.at}' on line 35, col 27
        if _v is not None: write(_filter(_v, rawExpr='${unicode.at}')) # from line 35, col 27.
        write(''':
            b.task.run "completions"
        ;;
        #=====================================================================
        # BEGIN TASKS ========================================================
        #=====================================================================
        xjava)
            b.task.run "$''')
        _v = VFFSL(SL,"unicode.at",True) # '${unicode.at}' on line 42, col 27
        if _v is not None: write(_filter(_v, rawExpr='${unicode.at}')) # from line 42, col 27.
        write('''"
        ;;
        #=====================================================================
        # END ================================================================
        #=====================================================================
        x*)
            b.task.run "default" "$''')
        _v = VFFSL(SL,"unicode.at",True) # '${unicode.at}' on line 48, col 37
        if _v is not None: write(_filter(_v, rawExpr='${unicode.at}')) # from line 48, col 37.
        write('''"
        ;;
        esac
    else
        b.task.run "usage"
    fi
}

b.try.do run "$''')
        _v = VFFSL(SL,"unicode.at",True) # '${unicode.at}' on line 56, col 17
        if _v is not None: write(_filter(_v, rawExpr='${unicode.at}')) # from line 56, col 17.
        write('''"
b.catch FileNotFoundException ''')
        _v = VFFSL(SL,"cmd.name",True) # '${cmd.name}' on line 57, col 31
        if _v is not None: write(_filter(_v, rawExpr='${cmd.name}')) # from line 57, col 31.
        write('''.exception.file_not_found
b.catch StringIsNullException ''')
        _v = VFFSL(SL,"cmd.name",True) # '${cmd.name}' on line 58, col 31
        if _v is not None: write(_filter(_v, rawExpr='${cmd.name}')) # from line 58, col 31.
        write('''.exception.string_is_null
#b.finally try_again
b.try.end

# vim: set ts=4 sw=4 tw=78 ft=sh:
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_template = 'respond'

## END CLASS DEFINITION

if not hasattr(template, '_initCheetahAttributes'):
    templateAPIClass = getattr(template,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(template)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit https://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=template()).run()


