#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1550588530.459869
__CHEETAH_genTimestamp__ = 'Tue Feb 19 12:02:10 2019'
__CHEETAH_src__ = '../m/ADT_h.tmpl'
__CHEETAH_srcLastModified__ = 'Thu Mar  8 03:24:24 2018'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class ADT_h(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(ADT_h, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''#ifndef ''')
        _v = VFN(VFFSL(SL,"adt.name",True),"upper",False)() # u'${adt.name.upper()}' on line 1, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.name.upper()}')) # from line 1, col 10.
        write(u'''_H
#define ''')
        _v = VFN(VFFSL(SL,"adt.name",True),"upper",False)() # u'${adt.name.upper()}' on line 2, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.name.upper()}')) # from line 2, col 10.
        write(u'''_H

''')
        if len(VFFSL(SL,"adt.include",True)) > 0: # generated from line 4, col 1
            for i in range(0, len(VFFSL(SL,"adt.include",True))): # generated from line 5, col 1
                write(u'''#include "''')
                _v = VFN(VFN(VFFSL(SL,"adt",True),"include",True)[i],"name",True) # u'$adt.include[i].name' on line 6, col 12
                if _v is not None: write(_filter(_v, rawExpr=u'$adt.include[i].name')) # from line 6, col 12.
                write(u'''"
''')
        write(u'''
/*
A pointer to an incomplete type (hides the implementation details).
*/
typedef struct ''')
        _v = VFN(VFFSL(SL,"adt.name",True),"capitalize",False)() # u'${adt.name.capitalize()}' on line 13, col 16
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.name.capitalize()}')) # from line 13, col 16.
        write(u'''* ''')
        _v = VFN(VFFSL(SL,"adt.name",True),"capitalize",False)() # u'${adt.name.capitalize()}' on line 13, col 42
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.name.capitalize()}')) # from line 13, col 42.
        _v = VFFSL(SL,"adt.ptr",True) # u'${adt.ptr}' on line 13, col 66
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.ptr}')) # from line 13, col 66.
        write(u''';

/*
Create a ''')
        _v = VFN(VFFSL(SL,"adt.name",True),"capitalize",False)() # u'${adt.name.capitalize()}' on line 16, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.name.capitalize()}')) # from line 16, col 10.
        write(u''' and return a handle to it.
*/
''')
        _v = VFN(VFFSL(SL,"adt.name",True),"capitalize",False)() # u'${adt.name.capitalize()}' on line 18, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.name.capitalize()}')) # from line 18, col 1.
        _v = VFFSL(SL,"adt.ptr",True) # u'${adt.ptr}' on line 18, col 25
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.ptr}')) # from line 18, col 25.
        write(u''' create''')
        _v = VFN(VFFSL(SL,"adt.name",True),"capitalize",False)() # u'${adt.name.capitalize()}' on line 18, col 42
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.name.capitalize()}')) # from line 18, col 42.
        if len(VFFSL(SL,"adt.ctor",True)) > 1: # generated from line 19, col 1
            write(u''' (''')
            for i in range(0, len(VFFSL(SL,"adt.ctor",True))-1): # generated from line 21, col 1
                _v = VFN(VFN(VFFSL(SL,"adt",True),"ctor",True)[i],"type",True) # u'${adt.ctor[i].type}' on line 22, col 1
                if _v is not None: write(_filter(_v, rawExpr=u'${adt.ctor[i].type}')) # from line 22, col 1.
                write(u''' ''')
                _v = VFN(VFN(VFFSL(SL,"adt",True),"ctor",True)[i],"name",True) # u'${adt.ctor[i].name}' on line 22, col 21
                if _v is not None: write(_filter(_v, rawExpr=u'${adt.ctor[i].name}')) # from line 22, col 21.
                write(u''', ''')
            _v = VFN(VFN(VFFSL(SL,"adt",True),"ctor",True)[-1],"type",True) # u'${adt.ctor[-1].type}' on line 24, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'${adt.ctor[-1].type}')) # from line 24, col 1.
            write(u''' ''')
            _v = VFN(VFN(VFFSL(SL,"adt",True),"ctor",True)[-1],"name",True) # u'${adt.ctor[-1].name}' on line 24, col 22
            if _v is not None: write(_filter(_v, rawExpr=u'${adt.ctor[-1].name}')) # from line 24, col 22.
            write(u''');
''')
        else: # generated from line 26, col 1
            if len(VFFSL(SL,"adt.ctor",True)) == 0: # generated from line 27, col 1
                write(u'''();
''')
            else: # generated from line 29, col 1
                write(u'''(''')
                _v = VFN(VFN(VFFSL(SL,"adt",True),"ctor",True)[0],"type",True) # u'${adt.ctor[0].type}' on line 30, col 2
                if _v is not None: write(_filter(_v, rawExpr=u'${adt.ctor[0].type}')) # from line 30, col 2.
                write(u''' ''')
                _v = VFN(VFN(VFFSL(SL,"adt",True),"ctor",True)[0],"name",True) # u'${adt.ctor[0].name}' on line 30, col 22
                if _v is not None: write(_filter(_v, rawExpr=u'${adt.ctor[0].name}')) # from line 30, col 22.
                write(u''');
''')
        write(u'''
/*
Destroy the given ''')
        _v = VFN(VFFSL(SL,"adt.name",True),"capitalize",False)() # u'${adt.name.capitalize()}' on line 35, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.name.capitalize()}')) # from line 35, col 19.
        write(u''' object.
All handles to it will be invalidated.
*/
void destroy''')
        _v = VFN(VFFSL(SL,"adt.name",True),"capitalize",False)() # u'${adt.name.capitalize()}' on line 38, col 13
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.name.capitalize()}')) # from line 38, col 13.
        write(u'''
    (''')
        _v = VFN(VFFSL(SL,"adt.name",True),"capitalize",False)() # u'${adt.name.capitalize()}' on line 39, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.name.capitalize()}')) # from line 39, col 6.
        _v = VFFSL(SL,"adt.ptr",True) # u'${adt.ptr}' on line 39, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.ptr}')) # from line 39, col 30.
        write(u''' ''')
        _v = VFN(VFFSL(SL,"adt.name",True),"lower",False)() # u'${adt.name.lower()}' on line 39, col 41
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.name.lower()}')) # from line 39, col 41.
        write(u''');

void ''')
        _v = VFN(VFFSL(SL,"strategy.method",True),"lower",False)() # u'${strategy.method.lower()}' on line 41, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'${strategy.method.lower()}')) # from line 41, col 6.
        _v = VFN(VFFSL(SL,"strategy.name",True),"capitalize",False)() # u'${strategy.name.capitalize()}' on line 41, col 32
        if _v is not None: write(_filter(_v, rawExpr=u'${strategy.name.capitalize()}')) # from line 41, col 32.
        write(u'''Category''')
        if len(VFFSL(SL,"strategy.ctor",True)) > 1: # generated from line 42, col 1
            write(u'''(''')
            for i in range(0, len(VFFSL(SL,"strategy.ctor",True))-1): # generated from line 44, col 1
                _v = VFN(VFN(VFFSL(SL,"strategy",True),"ctor",True)[i],"type",True) # u'${strategy.ctor[i].type}' on line 45, col 1
                if _v is not None: write(_filter(_v, rawExpr=u'${strategy.ctor[i].type}')) # from line 45, col 1.
                write(u''' ''')
                _v = VFN(VFN(VFFSL(SL,"strategy",True),"ctor",True)[i],"name",True) # u'${strategy.ctor[i].name}' on line 45, col 26
                if _v is not None: write(_filter(_v, rawExpr=u'${strategy.ctor[i].name}')) # from line 45, col 26.
                write(u''', ''')
            _v = VFN(VFN(VFFSL(SL,"strategy",True),"ctor",True)[-1],"type",True) # u'${strategy.ctor[-1].type}' on line 47, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'${strategy.ctor[-1].type}')) # from line 47, col 1.
            write(u''' ''')
            _v = VFN(VFN(VFFSL(SL,"strategy",True),"ctor",True)[-1],"name",True) # u'${strategy.ctor[-1].name}' on line 47, col 27
            if _v is not None: write(_filter(_v, rawExpr=u'${strategy.ctor[-1].name}')) # from line 47, col 27.
            write(u''');
''')
        else: # generated from line 49, col 1
            if len(VFFSL(SL,"strategy.ctor",True)) == 0: # generated from line 50, col 1
                write(u'''();
''')
            else: # generated from line 52, col 1
                write(u'''(''')
                _v = VFN(VFN(VFFSL(SL,"strategy",True),"ctor",True)[0],"type",True) # u'${strategy.ctor[0].type}' on line 53, col 2
                if _v is not None: write(_filter(_v, rawExpr=u'${strategy.ctor[0].type}')) # from line 53, col 2.
                write(u''' ''')
                _v = VFN(VFN(VFFSL(SL,"strategy",True),"ctor",True)[0],"name",True) # u'${strategy.ctor[0].name}' on line 53, col 27
                if _v is not None: write(_filter(_v, rawExpr=u'${strategy.ctor[0].name}')) # from line 53, col 27.
                write(u''');
''')
        write(u'''#endif
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_ADT_h= 'respond'

## END CLASS DEFINITION

if not hasattr(ADT_h, '_initCheetahAttributes'):
    templateAPIClass = getattr(ADT_h, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(ADT_h)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=ADT_h()).run()


