#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1550588530.186316
__CHEETAH_genTimestamp__ = 'Tue Feb 19 12:02:10 2019'
__CHEETAH_src__ = '../m/ADTCategories_h.tmpl'
__CHEETAH_srcLastModified__ = 'Thu Mar  8 03:24:24 2018'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class ADTCategories_h(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(ADTCategories_h, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''#ifndef ''')
        _v = VFN(VFFSL(SL,"adt.name",True),"upper",False)() # u'${adt.name.upper()}' on line 1, col 9
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.name.upper()}')) # from line 1, col 9.
        write(u'''_CATEGORIES_H
#define ''')
        _v = VFN(VFFSL(SL,"adt.name",True),"upper",False)() # u'${adt.name.upper()}' on line 2, col 9
        if _v is not None: write(_filter(_v, rawExpr=u'${adt.name.upper()}')) # from line 2, col 9.
        write(u'''_CATEGORIES_H

''')
        if len(VFFSL(SL,"strategy.categories",True)) > 0: # generated from line 4, col 1
            for i in range(0, len(VFFSL(SL,"strategy.categories",True))): # generated from line 5, col 1
                _v = VFFSL(SL,"strategy.out",True) # u'${strategy.out}' on line 6, col 1
                if _v is not None: write(_filter(_v, rawExpr=u'${strategy.out}')) # from line 6, col 1.
                write(u''' ''')
                _v = VFN(VFN(VFFSL(SL,"strategy",True),"categories",True)[i],"name",True) # u'${strategy.categories[i].name}' on line 6, col 17
                if _v is not None: write(_filter(_v, rawExpr=u'${strategy.categories[i].name}')) # from line 6, col 17.
                _v = VFN(VFFSL(SL,"strategy.name",True),"capitalize",False)() # u'${strategy.name.capitalize()}' on line 6, col 47
                if _v is not None: write(_filter(_v, rawExpr=u'${strategy.name.capitalize()}')) # from line 6, col 47.
                write(u'''Strategy''')
                write(u''' (''')
                if len(VFFSL(SL,"strategy.in",True)) > 1: # generated from line 8, col 1
                    for j in range(0, len(VFFSL(SL,"strategy.in",True))-1): # generated from line 9, col 1
                        _v = VFN(VFFSL(SL,"strategy",True),"in",True)[j] # u'${strategy.in[j]}' on line 10, col 1
                        if _v is not None: write(_filter(_v, rawExpr=u'${strategy.in[j]}')) # from line 10, col 1.
                        write(u''', ''')
                    _v = VFN(VFFSL(SL,"strategy",True),"in",True)[-1] # u'${strategy.in[-1]}' on line 12, col 1
                    if _v is not None: write(_filter(_v, rawExpr=u'${strategy.in[-1]}')) # from line 12, col 1.
                    write(u''');

''')
                else: # generated from line 14, col 1
                    write(u'''(''')
                    _v = VFN(VFFSL(SL,"strategy",True),"in",True)[0] # u'${strategy.in[0]}' on line 15, col 2
                    if _v is not None: write(_filter(_v, rawExpr=u'${strategy.in[0]}')) # from line 15, col 2.
                    write(u''');

''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_ADTCategories_h= 'respond'

## END CLASS DEFINITION

if not hasattr(ADTCategories_h, '_initCheetahAttributes'):
    templateAPIClass = getattr(ADTCategories_h, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(ADTCategories_h)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=ADTCategories_h()).run()


